apiVersion: v1
kind: Service
metadata:
  name: leichte-sprache-backend
spec:
  ports:
  - name: http
    port: 7860
    protocol: TCP
    targetPort: 7860
  selector:
    app: leichte-sprache
  type: ClusterIP
