apiVersion: v1
kind: Service
metadata:
  name: leichte-sprache
  labels:
    app: leichte-sprache
spec:
  type: LoadBalancer
  selector:
    app: leichte-sprache
  ports:
    - name: http
      port: 7860
      targetPort: 7860
